name: Orbitez Production CI

on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    name: Deployment to production
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to production via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ./basemass
          git pull https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          cd ./orbitez
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 20
          npm i
          npm run build &&
          pm2 reload Basemass-FE-production
          cd ../server
          yarn
          pm2 reload Basemass-MainEU-Server-production
